# Generated by Django 4.0.6 on 2022-07-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
